# Server Configuration
server.port=8080

# Application Name
spring.application.name=compilecv

# Gemini API Configuration
gemini.api.key=AIzaSyANa38HFtWl4qBy0o6xHbteZrxK-k1YQ00
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Logging
logging.level.com.lockin.compilecv=DEBUG